import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { LeaveRequest } from '../src/models/leave.model';
import { User } from '../src/models/user.model';

dotenv.config();

const deleteLeaves = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI as string);
    console.log('Connected to MongoDB');

    // Find test users and candidates
    const demoUsers = await User.find({
      $or: [
        { email: 'test.employee@example.com' },
        { email: 'admin@gmail.com' }, // SuperAdmin leaves are just test data generated by the script
        { role: 'Candidate' }
      ]
    }).lean();

    const demoUserIds = demoUsers.map(u => u._id);

    console.log(`Found ${demoUserIds.length} demo/candidate users.`);

    const result = await LeaveRequest.deleteMany({
      userId: { $in: demoUserIds }
    });

    console.log(`Successfully deleted ${result.deletedCount} test/demo leave requests.`);

  } catch (error) {
    console.error('Error deleting records:', error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
  }
};

deleteLeaves();
